# These settings are synced to GitHub by https://probot.github.io/apps/settings/
# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  # A URL with more information about the repository
  homepage: https://cloudposse.com/accelerate
  # Either `true` to enable projects for this repository, or `false` to disable them.
  # If projects are disabled for the organization, passing `true` will cause an API error.
  has_projects: false
  # Either `true` to enable the wiki for this repository, `false` to disable it.
  has_wiki: false
  name: terraform-provider-utils
  description: The Cloud Posse Terraform Provider for various utilities (e.g. deep merging, stack configuration management)
  topics: terraform, terraform-providers, provider, utilities, utils, deep-merge, stack, config, configuration, configuration-management, spacelift
